# Generated by Django 3.1 on 2020-08-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200831_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping1',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.crust'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza.Topping'),
        ),
    ]
