# Generated by Django 3.1.1 on 2020-09-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20200831_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
